# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          20,    # Current Java LTS & minimum supported by Minecraft
        ]
        # and run on both Linux and Windows
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: read
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: Set environmental variables
        run: |
          echo "GITHUB_USERNAME=$GITHUB_ACTOR" >> $GITHUB_ENV
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-version: 8.1
          arguments: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '20' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Artifacts
          path: build/libs/
